# -*- coding: utf-8 -*-
"""hms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQikYpvUkTh6nVyPBPu9GXyk4KQlJlch
"""

import csv
import pandas as pd
class human:
  def __init__(self,id,name,age,gender):
    self.id = id
    self.name = name
    self.age = age
    self.gender = gender

class patient(human):
  def __init__(self,id,name,age,gender,disease):
    super().__init__(id,name,age,gender)
    self.disease = disease

  def __str__(self):
    return f"ID: {self.id},Name: {self.name},Age: {self.age},Gender: {self.gender},Disease: {self.disease}"

class doctor(human):
  def __init__(self,id,name,age,gender,specialization):
    super().__init__(id,name,age,gender)
    self.specialization = specialization

  def __str__(self):
    return f"ID: {self.id},Name: {self.name},Age: {self.age},Gender: {self.gender},Specialization: {self.specialization}"

class appointment:
  def __init__(self,id,patient,doctor,date):
    self.id = id
    self.patient = patient
    self.doctor = doctor
    self.date = date

  def __str__(self):
    return f"Patient's ID: {self.patient},Doctor's ID: {self.doctor},Date: {self.date}"

class Hospital_Management_System:
  def __init__(self):
    self.patients = []
    self.doctors = []
    self.appointments = []

  def addPatient(self,patient):
    self.patients.append(patient)

  def addDoctor(self,doctor):
    self.doctors.append(doctor)

  def setAppointment(self,appointment):
      self.appointments.append(appointment)

  def showpt(self):
    return [p.__str__() for p in self.patients]

  def showdr(self):
    return [p.__str__() for p in self.doctors]

  def showapp(self):
    return [p.__str__() for p in self.appointments]

  def export_patients_to_csv(self, filename="patients.csv"):
        with open(filename, mode="w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["ID", "Name", "Age", "Gender", "Disease"])
            for p in self.patients:
                writer.writerow([p.id, p.name, p.age, p.gender, p.disease])

  def export_doctors_to_csv(self, filename="doctors.csv"):
      with open(filename, mode="w", newline="") as file:
          writer = csv.writer(file)
          writer.writerow(["ID", "Name", "Age", "Gender", "specialization"])
          for d in self.doctors:
              writer.writerow([d.id, d.name, d.age, d.gender, d.specialization])

  def export_appointments_to_csv(self, filename="appointments.csv"):
      with open(filename, mode="w", newline="") as file:
          writer = csv.writer(file)
          writer.writerow(["Appointment ID", "Date", "Patient ID", "Patient Name", "Doctor ID", "Doctor Name"])
          for a in self.appointments:
              writer.writerow([a.id, a.date, a.patient.id, a.patient.name, a.doctor.id, a.doctor.name])