# -*- coding: utf-8 -*-
"""System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1TmNwS0sQ5c5wYkuMWebH9xhyAVxD5H
"""

import os
from hms import patient, doctor, appointment, Hospital_Management_System

hms= Hospital_Management_System()

def clear_screen():
    os.system("cls" if os.name == "nt" else "clear")

def mainMenu():
  while True:
    print("\n Welcome to Hospital Management System")
    print("Please choose one of the options below")
    print("1. Add Patient")
    print("2. Add Doctor")
    print("3. Set Appointment")
    print("4. View Patient")
    print("5. View Doctor")
    print("6. View Appointment")
    print("7. Export list of Patients")
    print("8. Export list of Doctors")
    print("9. Export list of Appointments")
    print("10. Exit")
    try:
      option = int(input("Enter your choice: "))
    except ValueError:
      print("Invalid input. Please enter a number.")
      continue
    match option:
      case 1 : add_patient()
      case 2 : add_doctor()
      case 3 : create_appointment()
      case 4 : list_patients()
      case 5 : list_doctors()
      case 6 : list_appointments()
      case 7 : hms.export_patients_to_csv()
      case 8 : hms.export_doctors_to_csv()
      case 9 : hms.export_appointments_to_csv()
      case 10 : break
      case _ : print("Invalid choice!");continue
    repeat = input("\nDo you want to perform another operation? (y/n): ").strip().lower()
    if repeat != 'y':
        print("Exiting...")
        break
    clear_screen()

def add_patient():
    pid = input("Patient ID: ")
    name = input("Name: ")
    age = int(input("Age: "))
    gender = input("Gender: ")
    disease = input("Disease: ")
    pat = patient(pid, name, age, gender, disease)
    hms.addPatient(pat)
    print("Patient added successfully!")

def add_doctor():
    did = input("Doctor ID: ")
    name = input("Name: ")
    age = int(input("Age: "))
    gender = input("Gender: ")
    specialty = input("Specialty: ")
    doc = doctor(did, name, age, gender, specialty)
    hms.addDoctor(doc)
    print("Doctor added successfully!")

def create_appointment():
    aid = input("Appointment ID: ")
    pid = input("Patient ID: ")
    did = input("Doctor ID: ")
    date = input("Date (YYYY-MM-DD): ")

    patient = next((p for p in hms.patients if p.id == pid), None)
    doctor = next((d for d in hms.doctors if d.id == did), None)

    if patient and doctor:
        a = appointment(aid, patient, doctor, date)
        hms.setAppointment(a)
        print("Appointment created!")
    else:
        print("Invalid patient or doctor ID!")

def list_patients():
    print("\n--- Patients List ---")
    for info in hms.showpt():
        print(info)

def list_doctors():
    print("\n--- Doctors List ---")
    for info in hms.showdr():
        print(info)

def list_appointments():
    print("\n--- Appointments List ---")
    for info in hms.showapp():
        print(info)

mainMenu()