# -*- coding: utf-8 -*-
"""Guessing_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBQLY5B3EbwRE3qNPdhvV9Tvy2QYrGXY

<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://lh3.googleusercontent.com/oEMY-qk_B2HW_Fponz1a3u1fLfo3NpO0VFjQKnVW8fH0v93NAWala5Kgp0nN2ubiyZdEMpwhv3Ynv7bXsB0RZ28YfEd_ZlRum75OHEu0-z7XwHfcD3sin7_SORLzg1gz52MsxD3b1WbxQWX1RdR4HP3jpbJTOuCiddl92UBcQH_x-Llx7_XuZuwb9ekN9vYnKsw6U1yL2df4IVrJEDySttzab9qlHvMO7sSekgS64jPVAmATjqXqlvrwM026dhrad-7nX-hfr2uKlUGPuo9xKzVo4EhbUP1-pKBQNPNHO6P0KcReg3NxbtKmWXRyg9LPX0xO-wwXWt9GhCcPXFV_BoY5eQXabCjR3mlr9SO01VgWplas-XF4337_JOm-bVkiaQjQca_N4Gg0hy26TvIGRnHEMIPSgudYPqhMnatoN4xAC715rP82r1svC0_qadXMZHu6D40YqWnY9ZE-iujr2p1_CetxmG-uY94UATy7o-SnxuPchG4QfZkiUgRMr8xNg86bQMuBxbCS_lOyVMwfqwbt2IunlDcZ8yyN_3SJFzFHuFOOjQolgGQrytI0mP1oTwba7je0RtBtCuTck1UCMMsZvMnJhCtWgMmuLoYTkSCzxMXbz0T3L2AClDouA_3dwM7z1gdm8Gq4v06T1KWFUs1adGNH5fuj-pUHEfW4drzzXgolPH5SehqhaNsqdMttCPUzNPIIEjwfULyQi7nlP-w-qydK82mdhdmjQhrprfoGtsPckJkI1Tur60uZI7nLkES5cE3tQrGualSNArRkkU8KN4tStZ0CkmqZNkAlMbfAJSYBD7tDxhGSg922AdLevSLJMTUyg6KuHoY30r7zH1Z8fE0R8aFZL2LJl54OU_tkXEdlFlSnZTOdB-PVTj-yagpt99SetLnQIX5SS_Vxc0BNPKjUZG0oEHYbIxkbZN1O7Rg78xe-thytngS0byfuaeP2X4NYjg29FIffnn72bAUs9Ii0N2mOpABLg1uQMN4MyAa1Mbd_=w1300-h200-no?authuser=1" >
      </a>

# Guessing Game Project Description

* **`First: You ask the user to set the game level:`**
  * *(1) Easy*:
    * Limits : [1 - 10]  
    * No. of trials : 3
  * *(2) Intermediate*:
    * Limits : [1 - 100]
    * No. of trials : 7
  * *(3) Hard* :  
    * Limits : [1 - 1000]
    * No. of trials : 15

* **`Second: set the game settings according to the game level:`**
  * set the `guess` to a number within the limits using `random` module
  * set the number of trials: `n_trials`

* **`Finally: Play the game:`**
  * Ask the user to guess the number:
    * If he guessed it successfully : `print('Congratulations, you achieved it in {user_trials} trial') `
    * if he failed:
      * user_trials < n_trials: till him (Increase) or (Decrease)
      * user_trials = n_trials: `print('You Lose!')`

# Solution

## Show the game levels
"""

def show_levels():
  print(''' Game Levels :
  (1) Easy:
      * Limits : [1 - 10]
      * No. of trials : 3
  (2) Intermediate*:
      * Limits : [1 - 100]
      * No. of trials : 7
  (3) Hard :
      * Limits : [1 - 1000]
      * No. of trials : 15 ''')

show_levels()

"""## Ask the user for the game level"""

def game_level_choice():
  while True:
      game_level = input('Enter the game level :\n (1) Easy \t (2) Intermediate \t (3) Hard \t')
      if game_level in ['1','2','3']:
          game_level = int(game_level)
          break
      else:
          print('Invalid Choice! Please choose 1, 2, or 3')
          continue
  return game_level

"""## Set the game settings according to the game level:

"""

def set_game_settings(game_level):
  if game_level == 1:
    limits = range(1,11)
    n_trials = 3
  elif game_level == 2:
    limits = range(1,101)
    n_trials = 7
  else:
    limits = range(1,1001)
    n_trials = 15
  return limits, n_trials

set_game_settings(2)

"""## Start Playing"""

import random

def start_play(limits, n_trials):
  hidden = random.choice(limits)
  user_trials = 0

  while user_trials < n_trials:
    guess = int(input('Guess the number :   '))
    user_trials +=1

    if guess == hidden:
      print(f'You got it successfully in {user_trials} trials')
      break
    else:
      if user_trials == n_trials:
        print(f"Unfortunately, You tried {user_trials} trials. No more Trials!")
        print(f'The hidden number is  {hidden}')
      elif guess < hidden:
        print('No, Increase!')
      else:
        print('No, Decrease!')
    continue

start_play(range(1, 11), 3)

"""# Play Again ?"""

def play_again():
    while True:
      play_again = input("Play again ? [0] No, [1] Yes:   ")
      if play_again in ['1','0']:
          break
      else:
          print('Invalid Choice! Please choose 0 or 1   ')
    return int(play_again)

play_again()

"""## Let's Play"""

def play():
  show_levels()
  while True:
    game_level = game_level_choice()
    limits, n_trials = set_game_settings(game_level)
    start_play(limits, n_trials)
    if not play_again():
        break

play()