# -*- coding: utf-8 -*-
"""World_Happiness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFt6sV6vq_y5w7eaNuOn_nVZZgM0ppEk

# **Please note that some of the visualizations are Interactive** <br>
**so you can move it around, select specific regions, or even explore the map to gian more insights on the dataset <br>
Have fun ♥**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv('/content/world-happiness-report-2021.csv')
df.head()

# Drop unnecessary columns
drop_cols = [
    'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
    'Ladder score in Dystopia', 'Explained by: Log GDP per capita',
    'Explained by: Social support', 'Explained by: Healthy life expectancy',
    'Explained by: Freedom to make life choices', 'Explained by: Generosity',
    'Explained by: Perceptions of corruption', 'Dystopia + residual'
]

df.drop(columns=drop_cols, inplace=True)

df.rename(columns={
    "Country name": "Country",
    "Regional indicator": "Region",
    "Ladder score": "Happiness",
    "Logged GDP per capita": "GDP",
    "Healthy life expectancy": "Life_Expectancy",
    "Freedom to make life choices": "Freedom",
    "Perceptions of corruption": "Corruption"
}, inplace=True)

df.info()

df.describe()

df.isnull().sum()

"""# Univariate Analysis"""

plt.figure(figsize=(10, 6))
sns.histplot(df['Happiness'], kde=True, color='blue')
plt.title("Distribution of Happiness Scores")
plt.show()

# Top 10 happiest
top_10 = df.sort_values('Happiness', ascending=False).head(10)
plt.figure(figsize=(12, 6))
sns.barplot(x='Happiness', y='Country', data=top_10, palette='viridis')
plt.title("Top 10 Happiest Countries")
plt.show()

# Bottom 10
bottom_10 = df.sort_values('Happiness').head(10)
plt.figure(figsize=(12, 6))
sns.barplot(x='Happiness', y='Country', data=bottom_10, palette='magma')
plt.title("10 Least Happy Countries")
plt.show()

"""# Bivariate Analysis"""

corr = df.corr(numeric_only=True)
plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Between Happiness Factors")
plt.show()

sns.pairplot(df[['Happiness', 'GDP', 'Social support', 'Life_Expectancy']])
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='Region', y='Happiness', data=df)
plt.xticks(rotation=90)
plt.title("Happiness Distribution by Region")
plt.show()

"""# Interactive Plot
Note that locations with grey color is not included in the dataset
"""

fig = px.choropleth(
    df,
    locations="Country",
    locationmode="country names",
    color="Happiness",
    hover_name="Country",
    title="World Happiness Map",
    color_continuous_scale=px.colors.sequential.Plasma
)
fig.show()

"""# Insights
- GDP, Social Support, and Life Expectancy  have the highest correlation with happiness.
- Happiest countries are (Finland, Denmark)
- Saddest countries are (Afghanistan, Zimbabwe)

# Multivariate Analysis
"""

sns.pairplot(df, hue='Region', palette='viridis')
plt.suptitle("Pairplot of Happiness Factors by Region", y=1.02)
plt.show()

num_cols = ['Happiness', 'GDP', 'Social support', 'Life_Expectancy', 'Freedom']
fig = px.scatter_matrix(
    df,
    dimensions=num_cols,
    color="Region",
    hover_name="Country",
    title="Pair Plot of Happiness Indicators"
)
fig.show()

fig = px.scatter_3d(
    df,
    x='GDP',
    y='Social support',
    z='Happiness',
    color='Region',
    hover_name='Country',
    title="Happiness vs. GDP & Social Support (3D)"
)
fig.update_layout(margin=dict(l=0, r=0, b=0, t=30))
fig.show()

fig = px.scatter(
    df,
    x="GDP",
    y="Happiness",
    size="Life_Expectancy",
    color="Region",
    hover_name="Country",
    size_max=20,
    title="Click legend to highlight regions"
)

fig.update_layout(
    clickmode='event+select',
    height=600
)

fig.show()