# -*- coding: utf-8 -*-
"""GuessTheWord.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jc1nrwx2TUlTJolSVqrvI-0aU9TzOSYJ

## Word Guessing Game Project

### Description:
Create a Python program that simulates a word guessing game with a limited number of trials.

### Objectives:
- Randomly select a word from a list.
- Display the word with guessed letters revealed and unguessed letters as dots.
- Allow the user to guess one letter at a time.
- Limit the number of incorrect guesses the user can make.
- Notify the user if their guess is correct or incorrect.
- End the game when the word is fully guessed or when the user runs out of trials.
- Display a congratulatory message if the word is guessed correctly or a game over message if the trials are exhausted.

### Features:
- **Random Word Selection:**
  - The program will randomly choose a word from a predefined list of words.
- **Word Display:**
  - The program will show the word with guessed letters revealed and the remaining letters as dots (e.g., "p.y.h.n").
- **User Input:**
  - The user will be prompted to enter a single letter in each attempt.
- **Guess Validation:**
  - The program will validate the user's input to ensure it is a single alphabetic character.
  - If the user guesses a letter that has already been guessed, they will be notified and asked to try another letter.
- **Tracking Trials:**
  - The program will keep count of how many incorrect guesses the user has made.
  - The game will end if the user reaches the maximum number of allowed incorrect guesses.
- **Feedback:**
  - The user will be informed if their guess is correct or incorrect.
- **Game Completion:**
  - The game continues until the user successfully guesses all the letters in the word or exhausts the allowed number of incorrect guesses.
  - Once the word is fully guessed, the program will congratulate the user.
  - If the user runs out of trials, the program will display a game over message with the correct word.
"""

import random

def words():
  word_list = ['apple','banana','guava','dragonfruit','mango']
  return random.choice(word_list)

def display(word,guess):
  display = ''
  for letter in word:
    if letter in guess:
      display += letter
    else:
      display += '.'
  return display

def main():
  guesses = set()
  max_trials = 5
  print("Welcome to the word guessing game ")
  while True:
    word = words()
    trials = 0
    guesses.clear()
    while trials < max_trials:
      print(display(word, guesses))
      user_guess = input("Please Enter a letter: ").lower().strip()
      if len(user_guess) != 1 or not user_guess.isalpha():
        print("Invalid input. Please enter a single letter.")
        continue
      if user_guess in guesses:
        print("You have already guessed that letter. Please try again.")
        continue
      guesses.add(user_guess)
      if user_guess in word:
        print("Correct guess!")
      else:
        print("Incorrect guess!")
        trials += 1
      if display(word, guesses) == word:
        print("Congratulations! You guessed the word:", word)
        break
    else:
      print("Game Over! The word was:", word)
    break

main()